name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
      - run: composer install --no-progress --no-interaction
      - run: composer ci:composer:validate
      - run: composer ci:yaml:lint
      - run: composer ci:php:cs
      - run: composer ci:php:stan

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4']
    steps:
      - uses: actions/checkout@v5
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer install --no-progress --no-interaction
      - run: composer ci:php:unit
